baseurl = "https://iotwx.github.io" 
title = "iotwx | open source weather stations"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "iotwx"
    info = "internet of things weather stations"
    description = "IOTWX Project website"
    keywords = "blog,developer,personal"
    avatarurl = "images/46693_anemometer_md.gif"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "open source iot smart weather stations for everyone, everywhere."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/iotwx"

#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab fa-2x"
#    weight = 2
#    url = "https://gitlab.com/"

#[[params.social]]
#    name = "Twitter"
#    icon = "fab fa-twitter fa-2x"
#    weight = 3
#    url = "https://twitter.com/johndoe/"

# Menu links

# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"

[[menu.main]]
    name = "Why?"
    weight = 2
    url = "/project/"

# [[menu.main]]
#     name = "How"
#     weight = 3
#     url = "/start/"

[[menu.main]]
    name = "Resources"
    weight = 3
    url = "/resources/"

[[menu.main]]
    name = "Get Involved"
    weight = 4
    url = "/getinvolved/"
